/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedClienteClienteRouteImport } from './routes/_authenticated/cliente.$cliente'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin/usuarios'
import { Route as AuthenticatedAdminServicosRouteImport } from './routes/_authenticated/admin/servicos'
import { Route as AuthenticatedAdminRelatoriosRouteImport } from './routes/_authenticated/admin/relatorios'
import { Route as AuthenticatedAdminEditorialRouteImport } from './routes/_authenticated/admin/editorial'
import { Route as AuthenticatedAdminDebugRouteImport } from './routes/_authenticated/admin/debug'
import { Route as AuthenticatedAdminClientesIndexRouteImport } from './routes/_authenticated/admin/clientes.index'
import { Route as AuthenticatedAdminUsuariosNovoRouteImport } from './routes/_authenticated/admin/usuarios.novo'
import { Route as AuthenticatedAdminDebugViewsRouteImport } from './routes/_authenticated/admin/debug.views'
import { Route as AuthenticatedAdminClientesNovoRouteImport } from './routes/_authenticated/admin/clientes.novo'
import { Route as AuthenticatedAdminClientesIdRouteImport } from './routes/_authenticated/admin/clientes.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedClienteClienteRoute =
  AuthenticatedClienteClienteRouteImport.update({
    id: '/cliente/$cliente',
    path: '/cliente/$cliente',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminServicosRoute =
  AuthenticatedAdminServicosRouteImport.update({
    id: '/servicos',
    path: '/servicos',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminRelatoriosRoute =
  AuthenticatedAdminRelatoriosRouteImport.update({
    id: '/relatorios',
    path: '/relatorios',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEditorialRoute =
  AuthenticatedAdminEditorialRouteImport.update({
    id: '/editorial',
    path: '/editorial',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDebugRoute = AuthenticatedAdminDebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminClientesIndexRoute =
  AuthenticatedAdminClientesIndexRouteImport.update({
    id: '/clientes/',
    path: '/clientes/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUsuariosNovoRoute =
  AuthenticatedAdminUsuariosNovoRouteImport.update({
    id: '/novo',
    path: '/novo',
    getParentRoute: () => AuthenticatedAdminUsuariosRoute,
  } as any)
const AuthenticatedAdminDebugViewsRoute =
  AuthenticatedAdminDebugViewsRouteImport.update({
    id: '/views',
    path: '/views',
    getParentRoute: () => AuthenticatedAdminDebugRoute,
  } as any)
const AuthenticatedAdminClientesNovoRoute =
  AuthenticatedAdminClientesNovoRouteImport.update({
    id: '/clientes/novo',
    path: '/clientes/novo',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminClientesIdRoute =
  AuthenticatedAdminClientesIdRouteImport.update({
    id: '/clientes/$id',
    path: '/clientes/$id',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/debug': typeof AuthenticatedAdminDebugRouteWithChildren
  '/admin/editorial': typeof AuthenticatedAdminEditorialRoute
  '/admin/relatorios': typeof AuthenticatedAdminRelatoriosRoute
  '/admin/servicos': typeof AuthenticatedAdminServicosRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRouteWithChildren
  '/cliente/$cliente': typeof AuthenticatedClienteClienteRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/clientes/$id': typeof AuthenticatedAdminClientesIdRoute
  '/admin/clientes/novo': typeof AuthenticatedAdminClientesNovoRoute
  '/admin/debug/views': typeof AuthenticatedAdminDebugViewsRoute
  '/admin/usuarios/novo': typeof AuthenticatedAdminUsuariosNovoRoute
  '/admin/clientes/': typeof AuthenticatedAdminClientesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/debug': typeof AuthenticatedAdminDebugRouteWithChildren
  '/admin/editorial': typeof AuthenticatedAdminEditorialRoute
  '/admin/relatorios': typeof AuthenticatedAdminRelatoriosRoute
  '/admin/servicos': typeof AuthenticatedAdminServicosRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRouteWithChildren
  '/cliente/$cliente': typeof AuthenticatedClienteClienteRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/clientes/$id': typeof AuthenticatedAdminClientesIdRoute
  '/admin/clientes/novo': typeof AuthenticatedAdminClientesNovoRoute
  '/admin/debug/views': typeof AuthenticatedAdminDebugViewsRoute
  '/admin/usuarios/novo': typeof AuthenticatedAdminUsuariosNovoRoute
  '/admin/clientes': typeof AuthenticatedAdminClientesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/admin/debug': typeof AuthenticatedAdminDebugRouteWithChildren
  '/_authenticated/admin/editorial': typeof AuthenticatedAdminEditorialRoute
  '/_authenticated/admin/relatorios': typeof AuthenticatedAdminRelatoriosRoute
  '/_authenticated/admin/servicos': typeof AuthenticatedAdminServicosRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRouteWithChildren
  '/_authenticated/cliente/$cliente': typeof AuthenticatedClienteClienteRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/clientes/$id': typeof AuthenticatedAdminClientesIdRoute
  '/_authenticated/admin/clientes/novo': typeof AuthenticatedAdminClientesNovoRoute
  '/_authenticated/admin/debug/views': typeof AuthenticatedAdminDebugViewsRoute
  '/_authenticated/admin/usuarios/novo': typeof AuthenticatedAdminUsuariosNovoRoute
  '/_authenticated/admin/clientes/': typeof AuthenticatedAdminClientesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/dashboard'
    | '/admin/debug'
    | '/admin/editorial'
    | '/admin/relatorios'
    | '/admin/servicos'
    | '/admin/usuarios'
    | '/cliente/$cliente'
    | '/admin/'
    | '/admin/clientes/$id'
    | '/admin/clientes/novo'
    | '/admin/debug/views'
    | '/admin/usuarios/novo'
    | '/admin/clientes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/admin/debug'
    | '/admin/editorial'
    | '/admin/relatorios'
    | '/admin/servicos'
    | '/admin/usuarios'
    | '/cliente/$cliente'
    | '/admin'
    | '/admin/clientes/$id'
    | '/admin/clientes/novo'
    | '/admin/debug/views'
    | '/admin/usuarios/novo'
    | '/admin/clientes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/admin/debug'
    | '/_authenticated/admin/editorial'
    | '/_authenticated/admin/relatorios'
    | '/_authenticated/admin/servicos'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/cliente/$cliente'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/clientes/$id'
    | '/_authenticated/admin/clientes/novo'
    | '/_authenticated/admin/debug/views'
    | '/_authenticated/admin/usuarios/novo'
    | '/_authenticated/admin/clientes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/cliente/$cliente': {
      id: '/_authenticated/cliente/$cliente'
      path: '/cliente/$cliente'
      fullPath: '/cliente/$cliente'
      preLoaderRoute: typeof AuthenticatedClienteClienteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/servicos': {
      id: '/_authenticated/admin/servicos'
      path: '/servicos'
      fullPath: '/admin/servicos'
      preLoaderRoute: typeof AuthenticatedAdminServicosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/relatorios': {
      id: '/_authenticated/admin/relatorios'
      path: '/relatorios'
      fullPath: '/admin/relatorios'
      preLoaderRoute: typeof AuthenticatedAdminRelatoriosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/editorial': {
      id: '/_authenticated/admin/editorial'
      path: '/editorial'
      fullPath: '/admin/editorial'
      preLoaderRoute: typeof AuthenticatedAdminEditorialRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/debug': {
      id: '/_authenticated/admin/debug'
      path: '/debug'
      fullPath: '/admin/debug'
      preLoaderRoute: typeof AuthenticatedAdminDebugRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/clientes/': {
      id: '/_authenticated/admin/clientes/'
      path: '/clientes'
      fullPath: '/admin/clientes/'
      preLoaderRoute: typeof AuthenticatedAdminClientesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/usuarios/novo': {
      id: '/_authenticated/admin/usuarios/novo'
      path: '/novo'
      fullPath: '/admin/usuarios/novo'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosNovoRouteImport
      parentRoute: typeof AuthenticatedAdminUsuariosRoute
    }
    '/_authenticated/admin/debug/views': {
      id: '/_authenticated/admin/debug/views'
      path: '/views'
      fullPath: '/admin/debug/views'
      preLoaderRoute: typeof AuthenticatedAdminDebugViewsRouteImport
      parentRoute: typeof AuthenticatedAdminDebugRoute
    }
    '/_authenticated/admin/clientes/novo': {
      id: '/_authenticated/admin/clientes/novo'
      path: '/clientes/novo'
      fullPath: '/admin/clientes/novo'
      preLoaderRoute: typeof AuthenticatedAdminClientesNovoRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/clientes/$id': {
      id: '/_authenticated/admin/clientes/$id'
      path: '/clientes/$id'
      fullPath: '/admin/clientes/$id'
      preLoaderRoute: typeof AuthenticatedAdminClientesIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminDebugRouteChildren {
  AuthenticatedAdminDebugViewsRoute: typeof AuthenticatedAdminDebugViewsRoute
}

const AuthenticatedAdminDebugRouteChildren: AuthenticatedAdminDebugRouteChildren =
  {
    AuthenticatedAdminDebugViewsRoute: AuthenticatedAdminDebugViewsRoute,
  }

const AuthenticatedAdminDebugRouteWithChildren =
  AuthenticatedAdminDebugRoute._addFileChildren(
    AuthenticatedAdminDebugRouteChildren,
  )

interface AuthenticatedAdminUsuariosRouteChildren {
  AuthenticatedAdminUsuariosNovoRoute: typeof AuthenticatedAdminUsuariosNovoRoute
}

const AuthenticatedAdminUsuariosRouteChildren: AuthenticatedAdminUsuariosRouteChildren =
  {
    AuthenticatedAdminUsuariosNovoRoute: AuthenticatedAdminUsuariosNovoRoute,
  }

const AuthenticatedAdminUsuariosRouteWithChildren =
  AuthenticatedAdminUsuariosRoute._addFileChildren(
    AuthenticatedAdminUsuariosRouteChildren,
  )

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminDebugRoute: typeof AuthenticatedAdminDebugRouteWithChildren
  AuthenticatedAdminEditorialRoute: typeof AuthenticatedAdminEditorialRoute
  AuthenticatedAdminRelatoriosRoute: typeof AuthenticatedAdminRelatoriosRoute
  AuthenticatedAdminServicosRoute: typeof AuthenticatedAdminServicosRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRouteWithChildren
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminClientesIdRoute: typeof AuthenticatedAdminClientesIdRoute
  AuthenticatedAdminClientesNovoRoute: typeof AuthenticatedAdminClientesNovoRoute
  AuthenticatedAdminClientesIndexRoute: typeof AuthenticatedAdminClientesIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminDebugRoute: AuthenticatedAdminDebugRouteWithChildren,
    AuthenticatedAdminEditorialRoute: AuthenticatedAdminEditorialRoute,
    AuthenticatedAdminRelatoriosRoute: AuthenticatedAdminRelatoriosRoute,
    AuthenticatedAdminServicosRoute: AuthenticatedAdminServicosRoute,
    AuthenticatedAdminUsuariosRoute:
      AuthenticatedAdminUsuariosRouteWithChildren,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
    AuthenticatedAdminClientesIdRoute: AuthenticatedAdminClientesIdRoute,
    AuthenticatedAdminClientesNovoRoute: AuthenticatedAdminClientesNovoRoute,
    AuthenticatedAdminClientesIndexRoute: AuthenticatedAdminClientesIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedClienteClienteRoute: typeof AuthenticatedClienteClienteRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedClienteClienteRoute: AuthenticatedClienteClienteRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
