/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthenticatedPlanoEstrategicoRouteImport } from './routes/_authenticated/plano-estrategico'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAprovacoesRouteImport } from './routes/_authenticated/aprovacoes'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedClienteClienteRouteImport } from './routes/_authenticated/cliente.$cliente'
import { Route as AuthenticatedAdminServicosRouteImport } from './routes/_authenticated/admin/servicos'
import { Route as AuthenticatedAdminRelatoriosRouteImport } from './routes/_authenticated/admin/relatorios'
import { Route as AuthenticatedAdminPlanoEstrategicoRouteImport } from './routes/_authenticated/admin/plano-estrategico'
import { Route as AuthenticatedAdminEditorialRouteImport } from './routes/_authenticated/admin/editorial'
import { Route as AuthenticatedAdminDebugRouteImport } from './routes/_authenticated/admin/debug'
import { Route as AuthenticatedAccountSecurityRouteImport } from './routes/_authenticated/account/security'
import { Route as AuthenticatedAdminKnowledgeRouteRouteImport } from './routes/_authenticated/admin/knowledge/route'
import { Route as AuthenticatedClienteClienteIndexRouteImport } from './routes/_authenticated/cliente.$cliente.index'
import { Route as AuthenticatedAdminUsuariosIndexRouteImport } from './routes/_authenticated/admin/usuarios.index'
import { Route as AuthenticatedAdminKnowledgeIndexRouteImport } from './routes/_authenticated/admin/knowledge/index'
import { Route as AuthenticatedAdminDebugIndexRouteImport } from './routes/_authenticated/admin/debug.index'
import { Route as AuthenticatedAdminClientesIndexRouteImport } from './routes/_authenticated/admin/clientes.index'
import { Route as AuthenticatedClienteClienteTiktokRouteImport } from './routes/_authenticated/cliente.$cliente.tiktok'
import { Route as AuthenticatedClienteClientePlanoEstrategicoRouteImport } from './routes/_authenticated/cliente.$cliente.plano-estrategico'
import { Route as AuthenticatedClienteClienteMetaAdsRouteImport } from './routes/_authenticated/cliente.$cliente.meta-ads'
import { Route as AuthenticatedClienteClienteInstagramRouteImport } from './routes/_authenticated/cliente.$cliente.instagram'
import { Route as AuthenticatedClienteClienteGoogleBusinessRouteImport } from './routes/_authenticated/cliente.$cliente.google-business'
import { Route as AuthenticatedClienteClienteGoogleAdsRouteImport } from './routes/_authenticated/cliente.$cliente.google-ads'
import { Route as AuthenticatedClienteClienteGa4RouteImport } from './routes/_authenticated/cliente.$cliente.ga4'
import { Route as AuthenticatedAdminUsuariosNovoRouteImport } from './routes/_authenticated/admin/usuarios.novo'
import { Route as AuthenticatedAdminUsuariosUserIdRouteImport } from './routes/_authenticated/admin/usuarios.$userId'
import { Route as AuthenticatedAdminKnowledgeSplatRouteImport } from './routes/_authenticated/admin/knowledge/$'
import { Route as AuthenticatedAdminDebugViewsRouteImport } from './routes/_authenticated/admin/debug.views'
import { Route as AuthenticatedAdminClientesNovoRouteImport } from './routes/_authenticated/admin/clientes.novo'
import { Route as AuthenticatedAdminClientesIdRouteImport } from './routes/_authenticated/admin/clientes.$id'
import { Route as AuthenticatedClienteClientePlanoEstrategicoIndexRouteImport } from './routes/_authenticated/cliente.$cliente.plano-estrategico.index'
import { Route as AuthenticatedClienteClientePlanoEstrategicoPlanoIdRouteImport } from './routes/_authenticated/cliente.$cliente.plano-estrategico.$planoId'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthenticatedPlanoEstrategicoRoute =
  AuthenticatedPlanoEstrategicoRouteImport.update({
    id: '/plano-estrategico',
    path: '/plano-estrategico',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAprovacoesRoute = AuthenticatedAprovacoesRouteImport.update({
  id: '/aprovacoes',
  path: '/aprovacoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedClienteClienteRoute =
  AuthenticatedClienteClienteRouteImport.update({
    id: '/cliente/$cliente',
    path: '/cliente/$cliente',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminServicosRoute =
  AuthenticatedAdminServicosRouteImport.update({
    id: '/servicos',
    path: '/servicos',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminRelatoriosRoute =
  AuthenticatedAdminRelatoriosRouteImport.update({
    id: '/relatorios',
    path: '/relatorios',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPlanoEstrategicoRoute =
  AuthenticatedAdminPlanoEstrategicoRouteImport.update({
    id: '/plano-estrategico',
    path: '/plano-estrategico',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEditorialRoute =
  AuthenticatedAdminEditorialRouteImport.update({
    id: '/editorial',
    path: '/editorial',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDebugRoute = AuthenticatedAdminDebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAccountSecurityRoute =
  AuthenticatedAccountSecurityRouteImport.update({
    id: '/account/security',
    path: '/account/security',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminKnowledgeRouteRoute =
  AuthenticatedAdminKnowledgeRouteRouteImport.update({
    id: '/knowledge',
    path: '/knowledge',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedClienteClienteIndexRoute =
  AuthenticatedClienteClienteIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedClienteClienteRoute,
  } as any)
const AuthenticatedAdminUsuariosIndexRoute =
  AuthenticatedAdminUsuariosIndexRouteImport.update({
    id: '/usuarios/',
    path: '/usuarios/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminKnowledgeIndexRoute =
  AuthenticatedAdminKnowledgeIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminKnowledgeRouteRoute,
  } as any)
const AuthenticatedAdminDebugIndexRoute =
  AuthenticatedAdminDebugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminDebugRoute,
  } as any)
const AuthenticatedAdminClientesIndexRoute =
  AuthenticatedAdminClientesIndexRouteImport.update({
    id: '/clientes/',
    path: '/clientes/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedClienteClienteTiktokRoute =
  AuthenticatedClienteClienteTiktokRouteImport.update({
    id: '/tiktok',
    path: '/tiktok',
    getParentRoute: () => AuthenticatedClienteClienteRoute,
  } as any)
const AuthenticatedClienteClientePlanoEstrategicoRoute =
  AuthenticatedClienteClientePlanoEstrategicoRouteImport.update({
    id: '/plano-estrategico',
    path: '/plano-estrategico',
    getParentRoute: () => AuthenticatedClienteClienteRoute,
  } as any)
const AuthenticatedClienteClienteMetaAdsRoute =
  AuthenticatedClienteClienteMetaAdsRouteImport.update({
    id: '/meta-ads',
    path: '/meta-ads',
    getParentRoute: () => AuthenticatedClienteClienteRoute,
  } as any)
const AuthenticatedClienteClienteInstagramRoute =
  AuthenticatedClienteClienteInstagramRouteImport.update({
    id: '/instagram',
    path: '/instagram',
    getParentRoute: () => AuthenticatedClienteClienteRoute,
  } as any)
const AuthenticatedClienteClienteGoogleBusinessRoute =
  AuthenticatedClienteClienteGoogleBusinessRouteImport.update({
    id: '/google-business',
    path: '/google-business',
    getParentRoute: () => AuthenticatedClienteClienteRoute,
  } as any)
const AuthenticatedClienteClienteGoogleAdsRoute =
  AuthenticatedClienteClienteGoogleAdsRouteImport.update({
    id: '/google-ads',
    path: '/google-ads',
    getParentRoute: () => AuthenticatedClienteClienteRoute,
  } as any)
const AuthenticatedClienteClienteGa4Route =
  AuthenticatedClienteClienteGa4RouteImport.update({
    id: '/ga4',
    path: '/ga4',
    getParentRoute: () => AuthenticatedClienteClienteRoute,
  } as any)
const AuthenticatedAdminUsuariosNovoRoute =
  AuthenticatedAdminUsuariosNovoRouteImport.update({
    id: '/usuarios/novo',
    path: '/usuarios/novo',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUsuariosUserIdRoute =
  AuthenticatedAdminUsuariosUserIdRouteImport.update({
    id: '/usuarios/$userId',
    path: '/usuarios/$userId',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminKnowledgeSplatRoute =
  AuthenticatedAdminKnowledgeSplatRouteImport.update({
    id: '/$',
    path: '/$',
    getParentRoute: () => AuthenticatedAdminKnowledgeRouteRoute,
  } as any)
const AuthenticatedAdminDebugViewsRoute =
  AuthenticatedAdminDebugViewsRouteImport.update({
    id: '/views',
    path: '/views',
    getParentRoute: () => AuthenticatedAdminDebugRoute,
  } as any)
const AuthenticatedAdminClientesNovoRoute =
  AuthenticatedAdminClientesNovoRouteImport.update({
    id: '/clientes/novo',
    path: '/clientes/novo',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminClientesIdRoute =
  AuthenticatedAdminClientesIdRouteImport.update({
    id: '/clientes/$id',
    path: '/clientes/$id',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedClienteClientePlanoEstrategicoIndexRoute =
  AuthenticatedClienteClientePlanoEstrategicoIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedClienteClientePlanoEstrategicoRoute,
  } as any)
const AuthenticatedClienteClientePlanoEstrategicoPlanoIdRoute =
  AuthenticatedClienteClientePlanoEstrategicoPlanoIdRouteImport.update({
    id: '/$planoId',
    path: '/$planoId',
    getParentRoute: () => AuthenticatedClienteClientePlanoEstrategicoRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/aprovacoes': typeof AuthenticatedAprovacoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/plano-estrategico': typeof AuthenticatedPlanoEstrategicoRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/': typeof AuthIndexRoute
  '/admin/knowledge': typeof AuthenticatedAdminKnowledgeRouteRouteWithChildren
  '/account/security': typeof AuthenticatedAccountSecurityRoute
  '/admin/debug': typeof AuthenticatedAdminDebugRouteWithChildren
  '/admin/editorial': typeof AuthenticatedAdminEditorialRoute
  '/admin/plano-estrategico': typeof AuthenticatedAdminPlanoEstrategicoRoute
  '/admin/relatorios': typeof AuthenticatedAdminRelatoriosRoute
  '/admin/servicos': typeof AuthenticatedAdminServicosRoute
  '/cliente/$cliente': typeof AuthenticatedClienteClienteRouteWithChildren
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/clientes/$id': typeof AuthenticatedAdminClientesIdRoute
  '/admin/clientes/novo': typeof AuthenticatedAdminClientesNovoRoute
  '/admin/debug/views': typeof AuthenticatedAdminDebugViewsRoute
  '/admin/knowledge/$': typeof AuthenticatedAdminKnowledgeSplatRoute
  '/admin/usuarios/$userId': typeof AuthenticatedAdminUsuariosUserIdRoute
  '/admin/usuarios/novo': typeof AuthenticatedAdminUsuariosNovoRoute
  '/cliente/$cliente/ga4': typeof AuthenticatedClienteClienteGa4Route
  '/cliente/$cliente/google-ads': typeof AuthenticatedClienteClienteGoogleAdsRoute
  '/cliente/$cliente/google-business': typeof AuthenticatedClienteClienteGoogleBusinessRoute
  '/cliente/$cliente/instagram': typeof AuthenticatedClienteClienteInstagramRoute
  '/cliente/$cliente/meta-ads': typeof AuthenticatedClienteClienteMetaAdsRoute
  '/cliente/$cliente/plano-estrategico': typeof AuthenticatedClienteClientePlanoEstrategicoRouteWithChildren
  '/cliente/$cliente/tiktok': typeof AuthenticatedClienteClienteTiktokRoute
  '/admin/clientes/': typeof AuthenticatedAdminClientesIndexRoute
  '/admin/debug/': typeof AuthenticatedAdminDebugIndexRoute
  '/admin/knowledge/': typeof AuthenticatedAdminKnowledgeIndexRoute
  '/admin/usuarios/': typeof AuthenticatedAdminUsuariosIndexRoute
  '/cliente/$cliente/': typeof AuthenticatedClienteClienteIndexRoute
  '/cliente/$cliente/plano-estrategico/$planoId': typeof AuthenticatedClienteClientePlanoEstrategicoPlanoIdRoute
  '/cliente/$cliente/plano-estrategico/': typeof AuthenticatedClienteClientePlanoEstrategicoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aprovacoes': typeof AuthenticatedAprovacoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/plano-estrategico': typeof AuthenticatedPlanoEstrategicoRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth': typeof AuthIndexRoute
  '/account/security': typeof AuthenticatedAccountSecurityRoute
  '/admin/editorial': typeof AuthenticatedAdminEditorialRoute
  '/admin/plano-estrategico': typeof AuthenticatedAdminPlanoEstrategicoRoute
  '/admin/relatorios': typeof AuthenticatedAdminRelatoriosRoute
  '/admin/servicos': typeof AuthenticatedAdminServicosRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/clientes/$id': typeof AuthenticatedAdminClientesIdRoute
  '/admin/clientes/novo': typeof AuthenticatedAdminClientesNovoRoute
  '/admin/debug/views': typeof AuthenticatedAdminDebugViewsRoute
  '/admin/knowledge/$': typeof AuthenticatedAdminKnowledgeSplatRoute
  '/admin/usuarios/$userId': typeof AuthenticatedAdminUsuariosUserIdRoute
  '/admin/usuarios/novo': typeof AuthenticatedAdminUsuariosNovoRoute
  '/cliente/$cliente/ga4': typeof AuthenticatedClienteClienteGa4Route
  '/cliente/$cliente/google-ads': typeof AuthenticatedClienteClienteGoogleAdsRoute
  '/cliente/$cliente/google-business': typeof AuthenticatedClienteClienteGoogleBusinessRoute
  '/cliente/$cliente/instagram': typeof AuthenticatedClienteClienteInstagramRoute
  '/cliente/$cliente/meta-ads': typeof AuthenticatedClienteClienteMetaAdsRoute
  '/cliente/$cliente/tiktok': typeof AuthenticatedClienteClienteTiktokRoute
  '/admin/clientes': typeof AuthenticatedAdminClientesIndexRoute
  '/admin/debug': typeof AuthenticatedAdminDebugIndexRoute
  '/admin/knowledge': typeof AuthenticatedAdminKnowledgeIndexRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosIndexRoute
  '/cliente/$cliente': typeof AuthenticatedClienteClienteIndexRoute
  '/cliente/$cliente/plano-estrategico/$planoId': typeof AuthenticatedClienteClientePlanoEstrategicoPlanoIdRoute
  '/cliente/$cliente/plano-estrategico': typeof AuthenticatedClienteClientePlanoEstrategicoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/aprovacoes': typeof AuthenticatedAprovacoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/plano-estrategico': typeof AuthenticatedPlanoEstrategicoRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/': typeof AuthIndexRoute
  '/_authenticated/admin/knowledge': typeof AuthenticatedAdminKnowledgeRouteRouteWithChildren
  '/_authenticated/account/security': typeof AuthenticatedAccountSecurityRoute
  '/_authenticated/admin/debug': typeof AuthenticatedAdminDebugRouteWithChildren
  '/_authenticated/admin/editorial': typeof AuthenticatedAdminEditorialRoute
  '/_authenticated/admin/plano-estrategico': typeof AuthenticatedAdminPlanoEstrategicoRoute
  '/_authenticated/admin/relatorios': typeof AuthenticatedAdminRelatoriosRoute
  '/_authenticated/admin/servicos': typeof AuthenticatedAdminServicosRoute
  '/_authenticated/cliente/$cliente': typeof AuthenticatedClienteClienteRouteWithChildren
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/clientes/$id': typeof AuthenticatedAdminClientesIdRoute
  '/_authenticated/admin/clientes/novo': typeof AuthenticatedAdminClientesNovoRoute
  '/_authenticated/admin/debug/views': typeof AuthenticatedAdminDebugViewsRoute
  '/_authenticated/admin/knowledge/$': typeof AuthenticatedAdminKnowledgeSplatRoute
  '/_authenticated/admin/usuarios/$userId': typeof AuthenticatedAdminUsuariosUserIdRoute
  '/_authenticated/admin/usuarios/novo': typeof AuthenticatedAdminUsuariosNovoRoute
  '/_authenticated/cliente/$cliente/ga4': typeof AuthenticatedClienteClienteGa4Route
  '/_authenticated/cliente/$cliente/google-ads': typeof AuthenticatedClienteClienteGoogleAdsRoute
  '/_authenticated/cliente/$cliente/google-business': typeof AuthenticatedClienteClienteGoogleBusinessRoute
  '/_authenticated/cliente/$cliente/instagram': typeof AuthenticatedClienteClienteInstagramRoute
  '/_authenticated/cliente/$cliente/meta-ads': typeof AuthenticatedClienteClienteMetaAdsRoute
  '/_authenticated/cliente/$cliente/plano-estrategico': typeof AuthenticatedClienteClientePlanoEstrategicoRouteWithChildren
  '/_authenticated/cliente/$cliente/tiktok': typeof AuthenticatedClienteClienteTiktokRoute
  '/_authenticated/admin/clientes/': typeof AuthenticatedAdminClientesIndexRoute
  '/_authenticated/admin/debug/': typeof AuthenticatedAdminDebugIndexRoute
  '/_authenticated/admin/knowledge/': typeof AuthenticatedAdminKnowledgeIndexRoute
  '/_authenticated/admin/usuarios/': typeof AuthenticatedAdminUsuariosIndexRoute
  '/_authenticated/cliente/$cliente/': typeof AuthenticatedClienteClienteIndexRoute
  '/_authenticated/cliente/$cliente/plano-estrategico/$planoId': typeof AuthenticatedClienteClientePlanoEstrategicoPlanoIdRoute
  '/_authenticated/cliente/$cliente/plano-estrategico/': typeof AuthenticatedClienteClientePlanoEstrategicoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/aprovacoes'
    | '/dashboard'
    | '/plano-estrategico'
    | '/auth/callback'
    | '/auth/'
    | '/admin/knowledge'
    | '/account/security'
    | '/admin/debug'
    | '/admin/editorial'
    | '/admin/plano-estrategico'
    | '/admin/relatorios'
    | '/admin/servicos'
    | '/cliente/$cliente'
    | '/admin/'
    | '/admin/clientes/$id'
    | '/admin/clientes/novo'
    | '/admin/debug/views'
    | '/admin/knowledge/$'
    | '/admin/usuarios/$userId'
    | '/admin/usuarios/novo'
    | '/cliente/$cliente/ga4'
    | '/cliente/$cliente/google-ads'
    | '/cliente/$cliente/google-business'
    | '/cliente/$cliente/instagram'
    | '/cliente/$cliente/meta-ads'
    | '/cliente/$cliente/plano-estrategico'
    | '/cliente/$cliente/tiktok'
    | '/admin/clientes/'
    | '/admin/debug/'
    | '/admin/knowledge/'
    | '/admin/usuarios/'
    | '/cliente/$cliente/'
    | '/cliente/$cliente/plano-estrategico/$planoId'
    | '/cliente/$cliente/plano-estrategico/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aprovacoes'
    | '/dashboard'
    | '/plano-estrategico'
    | '/auth/callback'
    | '/auth'
    | '/account/security'
    | '/admin/editorial'
    | '/admin/plano-estrategico'
    | '/admin/relatorios'
    | '/admin/servicos'
    | '/admin'
    | '/admin/clientes/$id'
    | '/admin/clientes/novo'
    | '/admin/debug/views'
    | '/admin/knowledge/$'
    | '/admin/usuarios/$userId'
    | '/admin/usuarios/novo'
    | '/cliente/$cliente/ga4'
    | '/cliente/$cliente/google-ads'
    | '/cliente/$cliente/google-business'
    | '/cliente/$cliente/instagram'
    | '/cliente/$cliente/meta-ads'
    | '/cliente/$cliente/tiktok'
    | '/admin/clientes'
    | '/admin/debug'
    | '/admin/knowledge'
    | '/admin/usuarios'
    | '/cliente/$cliente'
    | '/cliente/$cliente/plano-estrategico/$planoId'
    | '/cliente/$cliente/plano-estrategico'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/aprovacoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/plano-estrategico'
    | '/auth/callback'
    | '/auth/'
    | '/_authenticated/admin/knowledge'
    | '/_authenticated/account/security'
    | '/_authenticated/admin/debug'
    | '/_authenticated/admin/editorial'
    | '/_authenticated/admin/plano-estrategico'
    | '/_authenticated/admin/relatorios'
    | '/_authenticated/admin/servicos'
    | '/_authenticated/cliente/$cliente'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/clientes/$id'
    | '/_authenticated/admin/clientes/novo'
    | '/_authenticated/admin/debug/views'
    | '/_authenticated/admin/knowledge/$'
    | '/_authenticated/admin/usuarios/$userId'
    | '/_authenticated/admin/usuarios/novo'
    | '/_authenticated/cliente/$cliente/ga4'
    | '/_authenticated/cliente/$cliente/google-ads'
    | '/_authenticated/cliente/$cliente/google-business'
    | '/_authenticated/cliente/$cliente/instagram'
    | '/_authenticated/cliente/$cliente/meta-ads'
    | '/_authenticated/cliente/$cliente/plano-estrategico'
    | '/_authenticated/cliente/$cliente/tiktok'
    | '/_authenticated/admin/clientes/'
    | '/_authenticated/admin/debug/'
    | '/_authenticated/admin/knowledge/'
    | '/_authenticated/admin/usuarios/'
    | '/_authenticated/cliente/$cliente/'
    | '/_authenticated/cliente/$cliente/plano-estrategico/$planoId'
    | '/_authenticated/cliente/$cliente/plano-estrategico/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_authenticated/plano-estrategico': {
      id: '/_authenticated/plano-estrategico'
      path: '/plano-estrategico'
      fullPath: '/plano-estrategico'
      preLoaderRoute: typeof AuthenticatedPlanoEstrategicoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/aprovacoes': {
      id: '/_authenticated/aprovacoes'
      path: '/aprovacoes'
      fullPath: '/aprovacoes'
      preLoaderRoute: typeof AuthenticatedAprovacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/cliente/$cliente': {
      id: '/_authenticated/cliente/$cliente'
      path: '/cliente/$cliente'
      fullPath: '/cliente/$cliente'
      preLoaderRoute: typeof AuthenticatedClienteClienteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/servicos': {
      id: '/_authenticated/admin/servicos'
      path: '/servicos'
      fullPath: '/admin/servicos'
      preLoaderRoute: typeof AuthenticatedAdminServicosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/relatorios': {
      id: '/_authenticated/admin/relatorios'
      path: '/relatorios'
      fullPath: '/admin/relatorios'
      preLoaderRoute: typeof AuthenticatedAdminRelatoriosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/plano-estrategico': {
      id: '/_authenticated/admin/plano-estrategico'
      path: '/plano-estrategico'
      fullPath: '/admin/plano-estrategico'
      preLoaderRoute: typeof AuthenticatedAdminPlanoEstrategicoRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/editorial': {
      id: '/_authenticated/admin/editorial'
      path: '/editorial'
      fullPath: '/admin/editorial'
      preLoaderRoute: typeof AuthenticatedAdminEditorialRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/debug': {
      id: '/_authenticated/admin/debug'
      path: '/debug'
      fullPath: '/admin/debug'
      preLoaderRoute: typeof AuthenticatedAdminDebugRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/account/security': {
      id: '/_authenticated/account/security'
      path: '/account/security'
      fullPath: '/account/security'
      preLoaderRoute: typeof AuthenticatedAccountSecurityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/knowledge': {
      id: '/_authenticated/admin/knowledge'
      path: '/knowledge'
      fullPath: '/admin/knowledge'
      preLoaderRoute: typeof AuthenticatedAdminKnowledgeRouteRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/cliente/$cliente/': {
      id: '/_authenticated/cliente/$cliente/'
      path: '/'
      fullPath: '/cliente/$cliente/'
      preLoaderRoute: typeof AuthenticatedClienteClienteIndexRouteImport
      parentRoute: typeof AuthenticatedClienteClienteRoute
    }
    '/_authenticated/admin/usuarios/': {
      id: '/_authenticated/admin/usuarios/'
      path: '/usuarios'
      fullPath: '/admin/usuarios/'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/knowledge/': {
      id: '/_authenticated/admin/knowledge/'
      path: '/'
      fullPath: '/admin/knowledge/'
      preLoaderRoute: typeof AuthenticatedAdminKnowledgeIndexRouteImport
      parentRoute: typeof AuthenticatedAdminKnowledgeRouteRoute
    }
    '/_authenticated/admin/debug/': {
      id: '/_authenticated/admin/debug/'
      path: '/'
      fullPath: '/admin/debug/'
      preLoaderRoute: typeof AuthenticatedAdminDebugIndexRouteImport
      parentRoute: typeof AuthenticatedAdminDebugRoute
    }
    '/_authenticated/admin/clientes/': {
      id: '/_authenticated/admin/clientes/'
      path: '/clientes'
      fullPath: '/admin/clientes/'
      preLoaderRoute: typeof AuthenticatedAdminClientesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/cliente/$cliente/tiktok': {
      id: '/_authenticated/cliente/$cliente/tiktok'
      path: '/tiktok'
      fullPath: '/cliente/$cliente/tiktok'
      preLoaderRoute: typeof AuthenticatedClienteClienteTiktokRouteImport
      parentRoute: typeof AuthenticatedClienteClienteRoute
    }
    '/_authenticated/cliente/$cliente/plano-estrategico': {
      id: '/_authenticated/cliente/$cliente/plano-estrategico'
      path: '/plano-estrategico'
      fullPath: '/cliente/$cliente/plano-estrategico'
      preLoaderRoute: typeof AuthenticatedClienteClientePlanoEstrategicoRouteImport
      parentRoute: typeof AuthenticatedClienteClienteRoute
    }
    '/_authenticated/cliente/$cliente/meta-ads': {
      id: '/_authenticated/cliente/$cliente/meta-ads'
      path: '/meta-ads'
      fullPath: '/cliente/$cliente/meta-ads'
      preLoaderRoute: typeof AuthenticatedClienteClienteMetaAdsRouteImport
      parentRoute: typeof AuthenticatedClienteClienteRoute
    }
    '/_authenticated/cliente/$cliente/instagram': {
      id: '/_authenticated/cliente/$cliente/instagram'
      path: '/instagram'
      fullPath: '/cliente/$cliente/instagram'
      preLoaderRoute: typeof AuthenticatedClienteClienteInstagramRouteImport
      parentRoute: typeof AuthenticatedClienteClienteRoute
    }
    '/_authenticated/cliente/$cliente/google-business': {
      id: '/_authenticated/cliente/$cliente/google-business'
      path: '/google-business'
      fullPath: '/cliente/$cliente/google-business'
      preLoaderRoute: typeof AuthenticatedClienteClienteGoogleBusinessRouteImport
      parentRoute: typeof AuthenticatedClienteClienteRoute
    }
    '/_authenticated/cliente/$cliente/google-ads': {
      id: '/_authenticated/cliente/$cliente/google-ads'
      path: '/google-ads'
      fullPath: '/cliente/$cliente/google-ads'
      preLoaderRoute: typeof AuthenticatedClienteClienteGoogleAdsRouteImport
      parentRoute: typeof AuthenticatedClienteClienteRoute
    }
    '/_authenticated/cliente/$cliente/ga4': {
      id: '/_authenticated/cliente/$cliente/ga4'
      path: '/ga4'
      fullPath: '/cliente/$cliente/ga4'
      preLoaderRoute: typeof AuthenticatedClienteClienteGa4RouteImport
      parentRoute: typeof AuthenticatedClienteClienteRoute
    }
    '/_authenticated/admin/usuarios/novo': {
      id: '/_authenticated/admin/usuarios/novo'
      path: '/usuarios/novo'
      fullPath: '/admin/usuarios/novo'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosNovoRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/usuarios/$userId': {
      id: '/_authenticated/admin/usuarios/$userId'
      path: '/usuarios/$userId'
      fullPath: '/admin/usuarios/$userId'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosUserIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/knowledge/$': {
      id: '/_authenticated/admin/knowledge/$'
      path: '/$'
      fullPath: '/admin/knowledge/$'
      preLoaderRoute: typeof AuthenticatedAdminKnowledgeSplatRouteImport
      parentRoute: typeof AuthenticatedAdminKnowledgeRouteRoute
    }
    '/_authenticated/admin/debug/views': {
      id: '/_authenticated/admin/debug/views'
      path: '/views'
      fullPath: '/admin/debug/views'
      preLoaderRoute: typeof AuthenticatedAdminDebugViewsRouteImport
      parentRoute: typeof AuthenticatedAdminDebugRoute
    }
    '/_authenticated/admin/clientes/novo': {
      id: '/_authenticated/admin/clientes/novo'
      path: '/clientes/novo'
      fullPath: '/admin/clientes/novo'
      preLoaderRoute: typeof AuthenticatedAdminClientesNovoRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/clientes/$id': {
      id: '/_authenticated/admin/clientes/$id'
      path: '/clientes/$id'
      fullPath: '/admin/clientes/$id'
      preLoaderRoute: typeof AuthenticatedAdminClientesIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/cliente/$cliente/plano-estrategico/': {
      id: '/_authenticated/cliente/$cliente/plano-estrategico/'
      path: '/'
      fullPath: '/cliente/$cliente/plano-estrategico/'
      preLoaderRoute: typeof AuthenticatedClienteClientePlanoEstrategicoIndexRouteImport
      parentRoute: typeof AuthenticatedClienteClientePlanoEstrategicoRoute
    }
    '/_authenticated/cliente/$cliente/plano-estrategico/$planoId': {
      id: '/_authenticated/cliente/$cliente/plano-estrategico/$planoId'
      path: '/$planoId'
      fullPath: '/cliente/$cliente/plano-estrategico/$planoId'
      preLoaderRoute: typeof AuthenticatedClienteClientePlanoEstrategicoPlanoIdRouteImport
      parentRoute: typeof AuthenticatedClienteClientePlanoEstrategicoRoute
    }
  }
}

interface AuthenticatedAdminKnowledgeRouteRouteChildren {
  AuthenticatedAdminKnowledgeSplatRoute: typeof AuthenticatedAdminKnowledgeSplatRoute
  AuthenticatedAdminKnowledgeIndexRoute: typeof AuthenticatedAdminKnowledgeIndexRoute
}

const AuthenticatedAdminKnowledgeRouteRouteChildren: AuthenticatedAdminKnowledgeRouteRouteChildren =
  {
    AuthenticatedAdminKnowledgeSplatRoute:
      AuthenticatedAdminKnowledgeSplatRoute,
    AuthenticatedAdminKnowledgeIndexRoute:
      AuthenticatedAdminKnowledgeIndexRoute,
  }

const AuthenticatedAdminKnowledgeRouteRouteWithChildren =
  AuthenticatedAdminKnowledgeRouteRoute._addFileChildren(
    AuthenticatedAdminKnowledgeRouteRouteChildren,
  )

interface AuthenticatedAdminDebugRouteChildren {
  AuthenticatedAdminDebugViewsRoute: typeof AuthenticatedAdminDebugViewsRoute
  AuthenticatedAdminDebugIndexRoute: typeof AuthenticatedAdminDebugIndexRoute
}

const AuthenticatedAdminDebugRouteChildren: AuthenticatedAdminDebugRouteChildren =
  {
    AuthenticatedAdminDebugViewsRoute: AuthenticatedAdminDebugViewsRoute,
    AuthenticatedAdminDebugIndexRoute: AuthenticatedAdminDebugIndexRoute,
  }

const AuthenticatedAdminDebugRouteWithChildren =
  AuthenticatedAdminDebugRoute._addFileChildren(
    AuthenticatedAdminDebugRouteChildren,
  )

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminKnowledgeRouteRoute: typeof AuthenticatedAdminKnowledgeRouteRouteWithChildren
  AuthenticatedAdminDebugRoute: typeof AuthenticatedAdminDebugRouteWithChildren
  AuthenticatedAdminEditorialRoute: typeof AuthenticatedAdminEditorialRoute
  AuthenticatedAdminPlanoEstrategicoRoute: typeof AuthenticatedAdminPlanoEstrategicoRoute
  AuthenticatedAdminRelatoriosRoute: typeof AuthenticatedAdminRelatoriosRoute
  AuthenticatedAdminServicosRoute: typeof AuthenticatedAdminServicosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminClientesIdRoute: typeof AuthenticatedAdminClientesIdRoute
  AuthenticatedAdminClientesNovoRoute: typeof AuthenticatedAdminClientesNovoRoute
  AuthenticatedAdminUsuariosUserIdRoute: typeof AuthenticatedAdminUsuariosUserIdRoute
  AuthenticatedAdminUsuariosNovoRoute: typeof AuthenticatedAdminUsuariosNovoRoute
  AuthenticatedAdminClientesIndexRoute: typeof AuthenticatedAdminClientesIndexRoute
  AuthenticatedAdminUsuariosIndexRoute: typeof AuthenticatedAdminUsuariosIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminKnowledgeRouteRoute:
      AuthenticatedAdminKnowledgeRouteRouteWithChildren,
    AuthenticatedAdminDebugRoute: AuthenticatedAdminDebugRouteWithChildren,
    AuthenticatedAdminEditorialRoute: AuthenticatedAdminEditorialRoute,
    AuthenticatedAdminPlanoEstrategicoRoute:
      AuthenticatedAdminPlanoEstrategicoRoute,
    AuthenticatedAdminRelatoriosRoute: AuthenticatedAdminRelatoriosRoute,
    AuthenticatedAdminServicosRoute: AuthenticatedAdminServicosRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
    AuthenticatedAdminClientesIdRoute: AuthenticatedAdminClientesIdRoute,
    AuthenticatedAdminClientesNovoRoute: AuthenticatedAdminClientesNovoRoute,
    AuthenticatedAdminUsuariosUserIdRoute:
      AuthenticatedAdminUsuariosUserIdRoute,
    AuthenticatedAdminUsuariosNovoRoute: AuthenticatedAdminUsuariosNovoRoute,
    AuthenticatedAdminClientesIndexRoute: AuthenticatedAdminClientesIndexRoute,
    AuthenticatedAdminUsuariosIndexRoute: AuthenticatedAdminUsuariosIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedClienteClientePlanoEstrategicoRouteChildren {
  AuthenticatedClienteClientePlanoEstrategicoPlanoIdRoute: typeof AuthenticatedClienteClientePlanoEstrategicoPlanoIdRoute
  AuthenticatedClienteClientePlanoEstrategicoIndexRoute: typeof AuthenticatedClienteClientePlanoEstrategicoIndexRoute
}

const AuthenticatedClienteClientePlanoEstrategicoRouteChildren: AuthenticatedClienteClientePlanoEstrategicoRouteChildren =
  {
    AuthenticatedClienteClientePlanoEstrategicoPlanoIdRoute:
      AuthenticatedClienteClientePlanoEstrategicoPlanoIdRoute,
    AuthenticatedClienteClientePlanoEstrategicoIndexRoute:
      AuthenticatedClienteClientePlanoEstrategicoIndexRoute,
  }

const AuthenticatedClienteClientePlanoEstrategicoRouteWithChildren =
  AuthenticatedClienteClientePlanoEstrategicoRoute._addFileChildren(
    AuthenticatedClienteClientePlanoEstrategicoRouteChildren,
  )

interface AuthenticatedClienteClienteRouteChildren {
  AuthenticatedClienteClienteGa4Route: typeof AuthenticatedClienteClienteGa4Route
  AuthenticatedClienteClienteGoogleAdsRoute: typeof AuthenticatedClienteClienteGoogleAdsRoute
  AuthenticatedClienteClienteGoogleBusinessRoute: typeof AuthenticatedClienteClienteGoogleBusinessRoute
  AuthenticatedClienteClienteInstagramRoute: typeof AuthenticatedClienteClienteInstagramRoute
  AuthenticatedClienteClienteMetaAdsRoute: typeof AuthenticatedClienteClienteMetaAdsRoute
  AuthenticatedClienteClientePlanoEstrategicoRoute: typeof AuthenticatedClienteClientePlanoEstrategicoRouteWithChildren
  AuthenticatedClienteClienteTiktokRoute: typeof AuthenticatedClienteClienteTiktokRoute
  AuthenticatedClienteClienteIndexRoute: typeof AuthenticatedClienteClienteIndexRoute
}

const AuthenticatedClienteClienteRouteChildren: AuthenticatedClienteClienteRouteChildren =
  {
    AuthenticatedClienteClienteGa4Route: AuthenticatedClienteClienteGa4Route,
    AuthenticatedClienteClienteGoogleAdsRoute:
      AuthenticatedClienteClienteGoogleAdsRoute,
    AuthenticatedClienteClienteGoogleBusinessRoute:
      AuthenticatedClienteClienteGoogleBusinessRoute,
    AuthenticatedClienteClienteInstagramRoute:
      AuthenticatedClienteClienteInstagramRoute,
    AuthenticatedClienteClienteMetaAdsRoute:
      AuthenticatedClienteClienteMetaAdsRoute,
    AuthenticatedClienteClientePlanoEstrategicoRoute:
      AuthenticatedClienteClientePlanoEstrategicoRouteWithChildren,
    AuthenticatedClienteClienteTiktokRoute:
      AuthenticatedClienteClienteTiktokRoute,
    AuthenticatedClienteClienteIndexRoute:
      AuthenticatedClienteClienteIndexRoute,
  }

const AuthenticatedClienteClienteRouteWithChildren =
  AuthenticatedClienteClienteRoute._addFileChildren(
    AuthenticatedClienteClienteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedAprovacoesRoute: typeof AuthenticatedAprovacoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPlanoEstrategicoRoute: typeof AuthenticatedPlanoEstrategicoRoute
  AuthenticatedAccountSecurityRoute: typeof AuthenticatedAccountSecurityRoute
  AuthenticatedClienteClienteRoute: typeof AuthenticatedClienteClienteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedAprovacoesRoute: AuthenticatedAprovacoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPlanoEstrategicoRoute: AuthenticatedPlanoEstrategicoRoute,
  AuthenticatedAccountSecurityRoute: AuthenticatedAccountSecurityRoute,
  AuthenticatedClienteClienteRoute:
    AuthenticatedClienteClienteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
